### ISSUE TITLE
DS 502 Assignments submission (sheet1 & 2)

### ISSUE THREAD

**Issue by Ma7moudAfify** [zeinabezz/DS502-2022-2023#4]
[Mahmoud_AbdElsalam_Mahmoud.pdf](https://github.com/zeinabezz/DS502-2022-2023/files/10003066/Mahmoud_AbdElsalam_Mahmoud.pdf)

**Comment by ahmedatteia** [comment]
DS 502 Assignments submission (sheet1 closed )

[Ahmed Mohamed Atteia Sheet1 closed .pdf](https://github.com/zeinabezz/DS502-2022-2023/files/10014968/Ahmed.Mohamed.Atteia.Sheet1.closed.pdf)

**Comment by zeinabezz** [comment]
Thanks recieved
