### ISSUE TITLE
Ahmed Mohamed Atteia sheet1 submission 

### ISSUE THREAD

**Issue by ahmedatteia** [zeinabezz/DS502-2022-2023#5]
[Ahmed Mohamed Atteia Sheet1 closed .pdf](https://github.com/zeinabezz/DS502-2022-2023/files/10015121/Ahmed.Mohamed.Atteia.Sheet1.closed.pdf)

**Comment by ahmedatteia** [comment]
[Ahmed Mohamed Atteia Sheet1 closed .pdf](https://github.com/zeinabezz/DS502-2022-2023/files/10015130/Ahmed.Mohamed.Atteia.Sheet1.closed.pdf)

**Comment by zeinabezz** [comment]
thanks recieved
