### ISSUE TITLE
Ahmed Mohamed Atteia sheet3 submission 

### ISSUE THREAD

**Issue by ahmedatteia** [zeinabezz/DS502-2022-2023#9]

**Comment by ahmedatteia** [comment]
[Ahmed_Mohamed_Atteia_Mohamed-sheet3_3Dec2022.zip](https://github.com/zeinabezz/DS502-2022-2023/files/10144607/Ahmed_Mohamed_Atteia_Mohamed-sheet3_3Dec2022.zip)

**Comment by ahmedatteia** [comment]
sheet 3 answers in attached file

**Comment by zeinabezz** [comment]
thanks
